# Generated by Django 6.1.1 on 2026-09-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='show_under_other',
            field=models.BooleanField(default=False, help_text="If checked, this category is grouped inside the 'Other' dropdown on the dashboard instead of getting its own card."),
        ),
    ]
