# Generated by Django 6.0.7 on 2026-09-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_more_other_bucket_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working'), ('idle', 'Idle / In Cupboard'), ('scrap', 'Scrap / Destroyed'), ('missing', 'Missing'), ('service', 'Under Service'), ('active', 'Active'), ('inactive', 'Inactive'), ('open', 'Open'), ('resolved', 'Resolved'), ('other', 'Other')], default='working', max_length=20),
        ),
    ]
