# Generated by Django 6.0.7 on 2026-09-21 06:21

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_status_running_stopped'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_assigned_to',
            field=models.CharField(blank=True, db_index=True, help_text='Current user / employee / location', max_length=150),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_location',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck if disposed/retired'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='linked_workstation',
            field=models.CharField(blank=True, db_index=True, help_text='Workstation ID this item is used in, e.g. WS004 (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(db_index=True, help_text='Short display name', max_length=150),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working'), ('idle', 'Idle / In Cupboard'), ('scrap', 'Scrap / Destroyed'), ('missing', 'Missing'), ('service', 'Under Service'), ('active', 'Active'), ('inactive', 'Inactive'), ('open', 'Open'), ('resolved', 'Resolved'), ('running', 'Running'), ('stopped', 'Stopped'), ('other', 'Other')], db_index=True, default='working', max_length=20),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='field_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'is_active', 'status'], name='assets_asse_categor_06d3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'is_active'], name='assets_asse_categor_da11d9_idx'),
        ),
        migrations.AddIndex(
            model_name='assethistory',
            index=models.Index(fields=['asset', '-changed_at'], name='assets_asse_asset_i_4d93ce_idx'),
        ),
    ]
