# Generated by Django 5.2.17 on 2026-09-22 03:50
# Purpose: cosmetic alignment only (help_text/related_name) + one new
# index. No column type/constraint changes — safe on top of the already-
# applied 0009_branch_asset_branch_userbranchaccess.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

INITIAL_BRANCHES = ["Chennai", "Tindivanam", "Kanchipuram", "Madurai"]


def seed_initial_branches(apps, schema_editor):
    """One-time convenience seed for the 4 starting branches, in case
    0009 (the migration that actually created the Branch table on this
    project) ran without it. Safe to run even if some/all already exist —
    get_or_create by name. Super Admin can add/rename/remove branches from
    the UI at any time afterwards."""
    Branch = apps.get_model("assets", "Branch")
    for name in INITIAL_BRANCHES:
        Branch.objects.get_or_create(
            name=name,
            defaults={"code": name.strip().upper()[:20], "status": True},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_branch_asset_branch_userbranchaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this asset belongs to. Null only for legacy rows imported before branches existed — assign one from the Edit page.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, help_text="Short code, e.g. 'CHN' (auto-filled from name if left blank)", max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.BooleanField(default=True, help_text='Uncheck to retire this branch without deleting it'),
        ),
        migrations.AlterField(
            model_name='userbranchaccess',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='admins', to='assets.branch'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['branch', 'is_active'], name='assets_asse_branch__965353_idx'),
        ),
        migrations.RunPython(seed_initial_branches, noop_reverse),
    ]
