# Generated by Django 5.2.17 on 2026-09-29 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_sitesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['code', 'name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working'), ('idle', 'Idle / In Cupboard'), ('scrap', 'Scrap / Destroyed'), ('missing', 'Missing'), ('service', 'Under Service'), ('active', 'Active'), ('inactive', 'Inactive'), ('open', 'Open'), ('resolved', 'Resolved'), ('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('not_set', 'Not Set'), ('other', 'Other')], db_index=True, default='working', max_length=20),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='asset',
            field=models.OneToOneField(help_text='The underlying Workstation Asset row (asset_tag, branch, status, audit history all live there, unchanged).', limit_choices_to={'category__name__iexact': 'workstation'}, on_delete=django.db.models.deletion.PROTECT, related_name='workstation_profile', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='extra_details',
            field=models.JSONField(blank=True, default=dict, help_text="All Workstation Field Builder values, keyed by WorkstationField.key — including Lookup fields, which store the linked asset(s)' asset_tag(s), same convention as Asset.extra_details."),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='unresolved',
            field=models.JSONField(blank=True, default=dict, help_text="Migration-time bookkeeping only: Lookup tokens from the legacy data that didn't resolve to a real Asset (blank / no match), kept here instead of silently dropped. Not shown on any form."),
        ),
        migrations.AlterField(
            model_name='workstationfield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workstationfield',
            name='key',
            field=models.CharField(help_text='Stable internal key stored in Workstation.extra_details. Auto-generated on creation; immutable afterwards.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='workstationfield',
            name='lookup_category',
            field=models.CharField(blank=True, help_text="AssetCategory name this field searches against, e.g. 'CPU / System Unit', 'Monitor', 'Employee'. Required for Lookup fields — the same searchable-combo-box behaviour Workstation's CPU/Monitor/etc. fields already have today.", max_length=100),
        ),
        migrations.AlterField(
            model_name='workstationfield',
            name='lookup_multi',
            field=models.BooleanField(default=False, help_text='Allow linking more than one asset (e.g. multiple Monitors or UPS units on one workstation).'),
        ),
        migrations.AlterField(
            model_name='workstationfieldoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workstationfieldoption',
            name='value',
            field=models.CharField(help_text='The value stored in Workstation.extra_details. Defaults to label if left blank.', max_length=200),
        ),
    ]
