# Generated by Django 5.2.17 on 2026-10-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_searchable_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(help_text='Unique ID, e.g. WS001, M009, K014, U006', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_assigned_to',
            field=models.CharField(blank=True, db_index=True, help_text='Current user / employee / location', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_location',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='linked_workstation',
            field=models.CharField(blank=True, db_index=True, help_text='Workstation ID this item is used in, e.g. WS004 (optional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model_number',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(db_index=True, help_text='Short display name', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='previous_assigned_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='previous_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(db_index=True, default='working', max_length=150),
        ),
    ]
