# Generated by Django 5.2.17 on 2026-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_alter_asset_asset_tag_alter_asset_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workstationfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
