# Generated by Django 5.2.17 on 2026-10-06 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_assetfield_max_length_workstationfield_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstationfield',
            name='lookup_category',
            field=models.ForeignKey(blank=True, help_text='AssetCategory this field searches against. Required for Lookup fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.assetcategory'),
        ),
    ]
