# Generated by Django 6.0.7 on 2026-10-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_alter_workstationfield_lookup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working'), ('idle', 'Idle / In Cupboard'), ('scrap', 'Scrap / Destroyed'), ('missing', 'Missing'), ('service', 'Under Service'), ('active', 'Active'), ('inactive', 'Inactive'), ('open', 'Open'), ('resolved', 'Resolved'), ('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('not_set', 'Not Set'), ('other', 'Other')], db_index=True, default='working', max_length=150),
        ),
    ]
