# Generated by Django 6.0.8 on 2026-10-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_assetfield_lookup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(db_index=True, default='working', max_length=150),
        ),
    ]
